import Navbar from "@/components/navbar/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";

import { Rubik, Playfair_Display } from "next/font/google";
import Footer from "@/components/footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

const playfair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  //👇 Add variable to our object
  variable: "--font-playfair",
});

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  //👇 Add variable to our object
  variable: "--font-rubik",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${rubik.variable}  ${playfair.variable} font-sans`}
    >
      <body>
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
